export default {
  LOAD_GAMES_REQUEST : 'LOAD_GAMES_REQUEST',
  LOAD_GAMES_SUCCESS : 'LOAD_GAMES_SUCCESS',
  LOAD_GAMES_FAILED : 'LOAD_GAMES_FAILED',
  ADD_GAME_SUCCESS : 'ADD_GAME_SUCCESS',
  ADD_GAME_REQUEST : 'ADD_GAME_REQUEST',
  ADD_GAME_FAILED : 'ADD_GAME_FAILED'
}